# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [434]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://github.com/guipsamora/pandas_exercises/blob/master/Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [2]:
import datetime
wind = pd.read_csv("wind.data", sep="\s+", parse_dates=[[0, 1, 2]] )
wind.head()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [3]:
def fix_century(x):
    year = x.year-100 if x.year>1989 else x.year
    return datetime.date(year, x.month, x.day)

wind['Yr_Mo_Dy'] = wind['Yr_Mo_Dy'].apply(fix_century)
wind.head()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [5]:
wind['Yr_Mo_Dy'] = pd.to_datetime(wind['Yr_Mo_Dy'])
wind = wind.set_index('Yr_Mo_Dy')
wind.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [8]:
wind.isnull()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-01,False,False,False,False,True,False,False,False,False,False,False,False
1961-01-02,False,True,False,False,False,False,False,False,False,False,False,False
1961-01-03,False,False,False,False,False,False,False,True,False,False,False,False
1961-01-04,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-05,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-06,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-07,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-08,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-09,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-10,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-11,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-12,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-13,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-14,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-15,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-16,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-17,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-18,False,False,False,False,True,False,False,False,False,False,False,False
1961-01-19,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-20,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-21,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-22,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-23,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-24,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-25,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-26,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-27,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-28,False,False,False,False,False,False,False,False,False,False,False,False
1961-01-29,True,False,False,False,False,False,False,False,False,False,False,False
1961-01-30,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-02,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-03,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-04,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-05,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-06,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-07,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-08,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-09,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-10,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-11,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-12,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-13,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-14,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-15,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-16,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-17,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-18,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-19,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-20,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-21,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-22,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-23,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-24,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-25,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-26,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-27,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-28,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-29,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-30,False,False,False,False,False,False,False,False,False,False,False,False
1978-12-31,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
wind.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [13]:
wind.shape[1] - wind.isnull().sum()

RPT     6
VAL     9
ROS    10
KIL     7
SHA    10
BIR    12
DUB     9
CLA    10
MUL     9
CLO    11
BEL    12
MAL     8
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [15]:
wind.mean().mean()

10.227982360836924

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [16]:
loc_stats = pd.DataFrame()

loc_stats['min'] = wind.min()
loc_stats['max'] = wind.max()
loc_stats['mean'] = wind.mean()
loc_stats['std'] = wind.std()

loc_stats

      min    max       mean       std
RPT  0.67  35.80  12.362987  5.618413
VAL  0.21  33.37  10.644314  5.267356
ROS  1.50  33.84  11.660526  5.008450
KIL  0.00  28.46   6.306468  3.605811
SHA  0.13  37.54  10.455834  4.936125
BIR  0.00  26.16   7.092254  3.968683
DUB  0.00  30.37   9.797343  4.977555
CLA  0.00  31.08   8.495053  4.499449
MUL  0.00  25.88   8.493590  4.166872
CLO  0.04  28.21   8.707332  4.503954
BEL  0.13  42.38  13.121007  5.835037
MAL  0.67  42.54  15.599079  6.699794

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [17]:
day_stats = pd.DataFrame()

day_stats['min'] = wind.min(axis=1)
day_stats['max'] = wind.max(axis=1)
day_stats['mean'] = wind.mean(axis=1)
day_stats['std'] = wind.std(axis=1)

day_stats

              min    max       mean       std
Yr_Mo_Dy
1961-01-01   9.29  18.50  13.018182  2.808875
1961-01-02   6.50  17.54  11.336364  3.188994
1961-01-03   6.17  18.50  11.641818  3.681912
1961-01-04   1.79  11.75   6.619167  3.198126
1961-01-05   6.17  13.33  10.630000  2.445356
1961-01-06   4.42  13.21   8.240000  2.998063
1961-01-07   4.96  14.29  10.385000  3.072114
1961-01-08   5.91  16.62  10.487500  3.547237
1961-01-09   4.75  15.37   9.897500  2.905954
1961-01-10   6.54  19.50  10.477500  3.442610
1961-01-11   2.79  20.71   9.625000  4.805082
1961-01-12   9.46  19.75  13.524167  3.375046
1961-01-13   0.58   9.92   4.277500  2.916349
1961-01-14   0.50   9.04   3.975833  2.788833
1961-01-15   2.37  12.04   6.695000  3.276740
1961-01-16   4.71  16.42  10.164167  3.521277
1961-01-17   8.71  17.75  13.621667  2.874739
1961-01-18   8.79  20.79  15.348182  4.128786
1961-01-19   1.04   7.83   4.111667  2.171325
1961-01-20   1.58  11.83   5.980000  3.017220
1961-01-21   6.13  14.33   9.302500  2.546210
1961-01-22   2.17  10.88   7.582500  2.485328
1961-01-23   9.96  20.58  14.034167  3.208592
1961-01-24  14.83  25.84  20.000833  4.178121
1961-01-25   6.04  17.50  10.965000  3.215017
1961-01-26  14.25  25.25  18.324167  3.639547
1961-01-27  16.13  27.63  19.845833  3.723692
1961-01-28   8.87  20.30  13.690833  3.444483
1961-01-29  17.54  27.71  22.024545  2.744060
1961-01-30   7.92  19.25  12.490833  3.513766
...           ...    ...        ...       ...
1978-12-02   5.13  19.95  10.975833  4.003148
1978-12-03  11.58  25.75  18.025000  3.829953
1978-12-04   1.71  17.96  10.293333  4.574457
1978-12-05   8.50  22.75  15.770833  4.054258
1978-12-06  16.04  34.46  23.283333  4.983313
1978-12-07  18.16  34.59  22.910000  4.542096
1978-12-08   3.37  17.33   9.108333  3.933222
1978-12-09   6.04  18.71  12.292500  3.774715
1978-12-10  13.00  26.08  17.910000  4.651189
1978-12-11  11.63  22.83  16.812500  3.177189
1978-12-12   8.29  23.13  13.400833  4.390385
1978-12-13   8.33  24.04  16.229167  4.573168
1978-12-14   3.37  19.75   9.551667  5.145011
1978-12-15   4.00  17.16   9.205833  4.513284
1978-12-16   2.46  18.08   9.245000  5.101314
1978-12-17   0.54   9.87   4.072500  3.193451
1978-12-18   1.00  19.79   8.820000  5.912305
1978-12-19   2.33  18.25   8.685000  4.289142
1978-12-20   0.42  12.38   5.025833  3.734645
1978-12-21   3.83  20.30   9.930833  4.495655
1978-12-22   2.46  13.08   7.000833  3.237337
1978-12-23   9.50  22.21  15.613333  3.850840
1978-12-24   4.79  31.71  10.823333  7.195039
1978-12-25   0.75  13.96   5.729167  3.583263
1978-12-26   1.96  13.83   6.523333  4.304510
1978-12-27   8.08  40.08  16.708333  7.868076
1978-12-28   5.00  41.46  15.150000  9.687857
1978-12-29   8.71  29.58  14.890000  5.756836
1978-12-30   9.13  28.79  15.367500  5.540437
1978-12-31   9.59  27.29  15.402500  5.702483

[6574 rows x 4 columns]

In [19]:
day_stats.head()

             min    max       mean       std
Yr_Mo_Dy
1961-01-01  9.29  18.50  13.018182  2.808875
1961-01-02  6.50  17.54  11.336364  3.188994
1961-01-03  6.17  18.50  11.641818  3.681912
1961-01-04  1.79  11.75   6.619167  3.198126
1961-01-05  6.17  13.33  10.630000  2.445356

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [20]:
wind['date'] = wind.index
wind['year'] = wind['date'].apply(lambda x : x.year)
wind['month'] = wind['date'].apply(lambda x : x.month)
wind['day'] = wind['date'].apply(lambda x : x.day)
wind.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date,year,month,day
Yr_Mo_Dy,,,,,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1961-01-01,1961,1,1
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,1961-01-02,1961,1,2
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,1961-01-03,1961,1,3
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,1961-01-04,1961,1,4
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,1961-01-05,1961,1,5

In [21]:
january_winds = wind.query('month == 1')
january_winds.loc[:, 'RPT':'MAL'].mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [22]:
wind.query("month == 1 and day == 1")

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date,year,month,day
Yr_Mo_Dy,,,,,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1961-01-01,1961,1,1
1962-01-01,9.29,3.42,11.54,3.50,2.21,1.96,10.41,2.79,3.54,5.17,4.38,7.92,1962-01-01,1962,1,1
1963-01-01,15.59,13.62,19.79,8.38,12.25,10.00,23.45,15.71,13.59,14.37,17.58,34.13,1963-01-01,1963,1,1
1964-01-01,25.80,22.13,18.21,13.25,21.29,14.79,14.12,19.58,13.25,16.75,28.96,21.00,1964-01-01,1964,1,1
1965-01-01,9.54,11.92,9.00,4.38,6.08,5.21,10.25,6.08,5.71,8.63,12.04,17.41,1965-01-01,1965,1,1
1966-01-01,22.04,21.50,17.08,12.75,22.17,15.59,21.79,18.12,16.66,17.83,28.33,23.79,1966-01-01,1966,1,1
1967-01-01,6.46,4.46,6.50,3.21,6.67,3.79,11.38,3.83,7.71,9.08,10.67,20.91,1967-01-01,1967,1,1
1968-01-01,30.04,17.88,16.25,16.25,21.79,12.54,18.16,16.62,18.75,17.62,22.25,27.29,1968-01-01,1968,1,1
1969-01-01,6.13,1.63,5.41,1.08,2.54,1.00,8.50,2.42,4.58,6.34,9.17,16.71,1969-01-01,1969,1,1
1970-01-01,9.59,2.96,11.79,3.42,6.13,4.08,9.00,4.46,7.29,3.50,7.33,13.00,1970-01-01,1970,1,1
1971-01-01,3.71,0.79,4.71,0.17,1.42,1.04,4.63,0.75,1.54,1.08,4.21,9.54,1971-01-01,1971,1,1
1972-01-01,9.29,3.63,14.54,4.25,6.75,4.42,13.00,5.33,10.04,8.54,8.71,19.17,1972-01-01,1972,1,1
1973-01-01,16.50,15.92,14.62,7.41,8.29,11.21,13.54,7.79,10.46,10.79,13.37,9.71,1973-01-01,1973,1,1
1974-01-01,23.21,16.54,16.08,9.75,15.83,11.46,9.54,13.54,13.83,16.66,17.21,25.29,1974-01-01,1974,1,1
1975-01-01,14.04,13.54,11.29,5.46,12.58,5.58,8.12,8.96,9.29,5.17,7.71,11.63,1975-01-01,1975,1,1
1976-01-01,18.34,17.67,14.83,8.00,16.62,10.13,13.17,9.04,13.13,5.75,11.38,14.96,1976-01-01,1976,1,1
1977-01-01,20.04,11.92,20.25,9.13,9.29,8.04,10.75,5.88,9.00,9.00,14.88,25.70,1977-01-01,1977,1,1
1978-01-01,8.33,7.12,7.71,3.54,8.50,7.50,14.71,10.00,11.83,10.00,15.09,20.46,1978-01-01,1978,1,1

### Step 13. Downsample the record to a monthly frequency for each location.

In [23]:
wind.query("month == 1")

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date,year,month,day
Yr_Mo_Dy,,,,,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1961-01-01,1961,1,1
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,1961-01-02,1961,1,2
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,1961-01-03,1961,1,3
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,1961-01-04,1961,1,4
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,1961-01-05,1961,1,5
1961-01-06,13.21,8.12,9.96,6.67,5.37,4.50,10.67,4.42,7.17,7.50,8.12,13.17,1961-01-06,1961,1,6
1961-01-07,13.50,14.29,9.50,4.96,12.29,8.33,9.17,9.29,7.58,7.96,13.96,13.79,1961-01-07,1961,1,7
1961-01-08,10.96,9.75,7.62,5.91,9.62,7.29,14.29,7.62,9.25,10.46,16.62,16.46,1961-01-08,1961,1,8
1961-01-09,12.58,10.83,10.00,4.75,10.37,6.79,8.04,10.13,7.79,9.08,13.04,15.37,1961-01-09,1961,1,9
1961-01-10,13.37,11.12,19.50,8.33,9.71,6.54,11.42,7.79,8.54,9.00,8.58,11.83,1961-01-10,1961,1,10
1961-01-11,10.58,9.87,8.42,2.79,8.71,7.25,7.54,8.33,5.71,8.67,20.71,16.92,1961-01-11,1961,1,11
1961-01-12,19.75,12.08,18.50,10.54,10.29,9.46,15.54,11.50,10.37,14.58,15.59,14.09,1961-01-12,1961,1,12
1961-01-13,9.92,3.54,8.46,2.96,2.29,0.96,4.63,0.58,2.33,3.37,5.25,7.04,1961-01-13,1961,1,13
1961-01-14,9.04,5.66,7.08,0.67,2.71,1.38,3.08,2.58,0.50,2.67,7.17,5.17,1961-01-14,1961,1,14
1961-01-15,12.04,9.67,11.75,2.37,7.38,3.13,2.50,6.83,4.75,5.63,7.54,6.75,1961-01-15,1961,1,15
1961-01-16,16.42,11.25,15.67,4.71,11.34,6.92,9.25,8.79,8.21,7.33,13.04,9.04,1961-01-16,1961,1,16
1961-01-17,17.75,14.37,17.33,10.13,13.96,13.37,13.42,11.04,8.71,11.38,15.92,16.08,1961-01-17,1961,1,17
1961-01-18,19.83,12.04,20.79,18.54,NaN,10.29,17.83,11.38,14.67,16.71,8.79,17.96,1961-01-18,1961,1,18
1961-01-19,4.92,3.42,7.29,1.04,3.67,3.17,3.71,2.79,1.92,2.71,6.87,7.83,1961-01-19,1961,1,19
1961-01-20,9.59,11.83,7.96,1.58,7.92,5.00,3.17,4.92,3.13,3.37,6.50,6.79,1961-01-20,1961,1,20
1961-01-21,14.33,10.25,11.92,6.13,10.04,7.67,8.04,9.17,7.04,7.87,6.75,12.42,1961-01-21,1961,1,21
1961-01-22,9.59,5.88,9.92,2.17,6.87,5.50,9.38,7.04,6.34,7.50,10.88,9.92,1961-01-22,1961,1,22
1961-01-23,16.54,9.96,18.54,10.46,13.50,12.67,13.70,13.75,10.75,13.17,14.79,20.58,1961-01-23,1961,1,23
1961-01-24,25.04,14.83,25.84,15.67,21.46,18.58,20.38,19.38,15.37,15.12,23.09,25.25,1961-01-24,1961,1,24
1961-01-25,13.62,11.17,12.67,6.04,10.00,9.42,9.25,8.71,7.12,12.04,14.04,17.50,1961-01-25,1961,1,25
1961-01-26,24.37,18.79,17.50,14.25,18.91,15.67,14.33,15.16,16.08,19.08,20.50,25.25,1961-01-26,1961,1,26
1961-01-27,22.04,20.79,17.41,16.21,19.04,16.13,16.79,18.29,18.66,19.08,26.08,27.63,1961-01-27,1961,1,27
1961-01-28,17.67,13.54,13.33,8.87,15.04,11.63,12.25,10.58,11.92,11.04,20.30,18.12,1961-01-28,1961,1,28
1961-01-29,NaN,23.91,22.29,17.54,24.08,19.70,22.00,20.25,21.46,19.95,27.71,23.38,1961-01-29,1961,1,29
1961-01-30,12.21,11.42,10.92,7.92,13.08,9.62,14.50,10.21,9.92,11.96,18.88,19.25,1961-01-30,1961,1,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978-01-02,14.62,11.83,10.50,7.41,14.21,9.62,17.08,13.46,13.50,11.67,22.63,27.92,1978-01-02,1978,1,2
1978-01-03,20.67,17.29,14.54,12.12,18.91,13.54,21.96,16.62,15.09,15.50,20.33,28.04,1978-01-03,1978,1,3
1978-01-04,12.96,10.67,7.62,6.42,13.88,8.50,8.38,11.83,5.91,3.75,14.29,15.29,1978-01-04,1978,1,4
1978-01-05,12.12,10.46,11.29,3.37,8.79,7.87,13.88,15.04,12.54,13.17,20.41,23.50,1978-01-05,1978,1,5
1978-01-06,16.50,13.83,14.21,6.42,9.87,9.54,11.29,12.87,11.12,13.21,20.41,21.62,1978-01-06,1978,1,6
1978-01-07,6.00,3.04,7.08,2.04,4.71,3.75,8.08,6.87,5.46,6.17,12.08,15.63,1978-01-07,1978,1,7
1978-01-08,9.21,11.58,6.63,2.04,8.38,7.83,8.12,12.04,7.25,10.46,19.75,20.75,1978-01-08,1978,1,8
1978-01-09,14.88,17.46,12.12,8.17,13.75,9.08,17.33,11.00,11.71,9.83,18.75,22.63,1978-01-09,1978,1,9
1978-01-10,16.38,21.54,14.42,9.42,16.83,9.50,16.62,10.29,12.17,10.29,19.46,19.79,1978-01-10,1978,1,10
1978-01-11,25.96,23.00,23.50,13.37,17.16,13.75,19.41,13.42,14.33,15.12,23.63,34.70,1978-01-11,1978,1,11
1978-01-12,13.00,8.67,18.66,6.29,6.38,5.29,11.58,4.54,5.91,6.13,9.87,19.79,1978-01-12,1978,1,12
1978-01-13,7.38,3.04,8.83,1.46,3.88,1.83,9.87,4.63,3.96,3.25,6.04,15.50,1978-01-13,1978,1,13
1978-01-14,4.67,1.08,8.04,2.79,2.33,0.71,4.17,1.21,1.67,2.37,3.96,10.63,1978-01-14,1978,1,14
1978-01-15,2.00,3.88,6.67,0.87,4.12,2.29,1.58,6.13,3.54,4.50,9.96,14.42,1978-01-15,1978,1,15
1978-01-16,14.79,11.92,12.83,5.37,8.50,5.04,7.87,6.38,7.04,5.46,8.75,13.25,1978-01-16,1978,1,16
1978-01-17,12.83,5.83,7.87,2.75,6.54,3.46,8.33,5.09,4.96,4.88,9.33,12.71,1978-01-17,1978,1,17
1978-01-18,12.92,10.63,12.42,4.79,11.87,7.67,7.92,8.50,8.04,8.12,13.62,17.00,1978-01-18,1978,1,18
1978-01-19,14.46,15.09,9.92,5.96,13.42,5.29,10.29,8.54,8.12,5.04,15.79,15.46,1978-01-19,1978,1,19
1978-01-20,15.00,11.75,10.21,6.46,11.83,7.17,13.79,11.79,10.92,10.08,14.88,19.58,1978-01-20,1978,1,20
1978-01-21,21.54,19.17,15.54,9.42,16.96,11.50,11.08,15.09,12.62,14.42,20.54,20.88,1978-01-21,1978,1,21
1978-01-22,15.12,14.62,10.79,7.71,13.88,8.38,15.71,10.08,11.92,10.25,13.29,20.38,1978-01-22,1978,1,22
1978-01-23,15.75,12.12,14.37,9.29,14.42,10.21,13.50,11.92,13.96,11.50,12.42,18.41,1978-01-23,1978,1,23
1978-01-24,11.21,5.37,8.17,6.83,7.41,6.58,13.92,8.54,9.75,8.83,12.29,25.75,1978-01-24,1978,1,24
1978-01-25,8.25,10.25,7.58,2.75,10.29,4.67,8.33,6.46,6.25,5.04,10.79,12.58,1978-01-25,1978,1,25
1978-01-26,13.08,11.29,10.04,6.67,13.75,7.00,16.50,10.88,12.04,10.96,17.88,26.42,1978-01-26,1978,1,26
1978-01-27,18.54,9.59,15.67,6.42,10.34,7.04,11.63,9.38,9.46,7.58,11.42,24.87,1978-01-27,1978,1,27
1978-01-28,35.38,29.88,18.00,15.96,26.92,15.67,15.87,26.34,15.04,17.75,34.42,35.83,1978-01-28,1978,1,28
1978-01-29,29.38,18.54,28.08,17.12,17.50,13.75,25.54,15.67,18.08,20.50,19.12,38.20,1978-01-29,1978,1,29
1978-01-30,9.62,8.71,9.59,2.71,7.58,3.54,6.08,6.08,5.33,4.46,10.41,12.83,1978-01-30,1978,1,30
1978-01-31,10.50,8.79,9.54,4.42,10.58,5.46,8.00,5.71,6.50,6.38,6.54,17.37,1978-01-31,1978,1,31

### Step 14. Downsample the record to a weekly frequency for each location.

In [31]:
wind[::7].head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date,year,month,day
Yr_Mo_Dy,,,,,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1961-01-01,1961,1,1
1961-01-08,10.96,9.75,7.62,5.91,9.62,7.29,14.29,7.62,9.25,10.46,16.62,16.46,1961-01-08,1961,1,8
1961-01-15,12.04,9.67,11.75,2.37,7.38,3.13,2.50,6.83,4.75,5.63,7.54,6.75,1961-01-15,1961,1,15
1961-01-22,9.59,5.88,9.92,2.17,6.87,5.50,9.38,7.04,6.34,7.50,10.88,9.92,1961-01-22,1961,1,22
1961-01-29,NaN,23.91,22.29,17.54,24.08,19.70,22.00,20.25,21.46,19.95,27.71,23.38,1961-01-29,1961,1,29

### Step 15. Calculate the mean windspeed for each month in the dataset.  
#### Treat January 1961 and January 1962 as *different* months.
#### (hint: first find a  way to create an identifier unique for each month.)

In [36]:
(wind.iloc[:, 0])

Yr_Mo_Dy
1961-01-01    15.04
1961-01-02    14.71
1961-01-03    18.50
1961-01-04    10.58
1961-01-05    13.33
1961-01-06    13.21
1961-01-07    13.50
1961-01-08    10.96
1961-01-09    12.58
1961-01-10    13.37
1961-01-11    10.58
1961-01-12    19.75
1961-01-13     9.92
1961-01-14     9.04
1961-01-15    12.04
1961-01-16    16.42
1961-01-17    17.75
1961-01-18    19.83
1961-01-19     4.92
1961-01-20     9.59
1961-01-21    14.33
1961-01-22     9.59
1961-01-23    16.54
1961-01-24    25.04
1961-01-25    13.62
1961-01-26    24.37
1961-01-27    22.04
1961-01-28    17.67
1961-01-29      NaN
1961-01-30    12.21
              ...
1978-12-02    13.70
1978-12-03    21.21
1978-12-04     9.92
1978-12-05    22.75
1978-12-06    29.33
1978-12-07    26.63
1978-12-08    12.92
1978-12-09    18.71
1978-12-10    24.92
1978-12-11    20.25
1978-12-12    23.13
1978-12-13    18.84
1978-12-14    17.21
1978-12-15    13.13
1978-12-16    14.88
1978-12-17     9.87
1978-12-18     9.83
1978-12-19    13.88
1978-12-20     9.92
1978-12-21    12.96
1978-12-22     6.21
1978-12-23    16.62
1978-12-24     8.67
1978-12-25     7.21
1978-12-26    13.83
1978-12-27    17.58
1978-12-28    13.21
1978-12-29    14.00
1978-12-30    18.50
1978-12-31    20.33
Name: RPT, Length: 6574, dtype: float64

### Step 16. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.