# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep="\t")

### Step 4. How many products cost more than $10.00?

In [3]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [4]:
removeDollar = lambda x: float(x[1:-1])
chipo.item_price = chipo.item_price.apply(removeDollar)

In [5]:
chipo[chipo['item_price']>10].item_price.count()

1130

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [31]:
temp_chipo = chipo.drop_duplicates(['item_name'])
price_per_item = temp_chipo[['item_price', 'item_name']]
price_per_item.sort_values(by='item_price', ascending=False)

      item_price                              item_name
281        23.78                       Steak Salad Bowl
445        22.20                                   Bowl
4          16.98                           Chicken Bowl
1229       11.89                    Barbacoa Salad Bowl
1132       11.89                    Carnitas Salad Bowl
7          11.75                          Steak Burrito
39         11.75                          Barbacoa Bowl
168        11.75                  Barbacoa Crispy Tacos
186        11.25                      Veggie Salad Bowl
738        11.25                      Veggie Soft Tacos
57         11.25                         Veggie Burrito
62         11.25                            Veggie Bowl
250        10.98                          Chicken Salad
92          9.25                     Steak Crispy Tacos
237         9.25                    Carnitas Soft Tacos
554         9.25                  Carnitas Crispy Tacos
8           9.25                       Steak Soft Tacos
56          9.25                    Barbacoa Soft Tacos
54          8.99                             Steak Bowl
664         8.99                            Steak Salad
3750        8.99                         Carnitas Salad
33          8.99                          Carnitas Bowl
27          8.99                       Carnitas Burrito
21          8.99                       Barbacoa Burrito
44          8.75                     Chicken Salad Bowl
11          8.75                   Chicken Crispy Tacos
12          8.75                     Chicken Soft Tacos
16          8.49                        Chicken Burrito
1694        8.49                           Veggie Salad
1653        8.49                    Veggie Crispy Tacos
1414        7.40                                  Salad
520         7.40                           Crispy Tacos
510         7.40                                Burrito
298         6.49                      6 Pack Soft Drink
10          4.45                    Chips and Guacamole
2           3.39                       Nantucket Nectar
1           3.39                                   Izze
674         3.00      Chips and Mild Fresh Tomato Salsa
233         2.95     Chips and Roasted Chili Corn Salsa
111         2.95    Chips and Tomatillo Red Chili Salsa
38          2.95  Chips and Tomatillo Green Chili Salsa
300         2.39    Chips and Tomatillo-Red Chili Salsa
191         2.39     Chips and Roasted Chili-Corn Salsa
3           2.39  Chips and Tomatillo-Green Chili Salsa
0           2.39           Chips and Fresh Tomato Salsa
18          2.18                            Canned Soda
40          2.15                                  Chips
6           1.69                          Side of Chips
263         1.25                      Canned Soft Drink
34          1.09                          Bottled Water

In [36]:
chipo[chipo['item_name'] == 'Steak Salad Bowl']

,order_id,quantity,item_name,choice_description,item_price
281,123,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",23.78
606,250,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Cheese, Gua...",11.89
607,250,1,Steak Salad Bowl,"[Fresh Tomato Salsa, Lettuce]",9.39
613,253,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",23.78
749,309,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Cheese, Lett...",11.89
1159,478,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.89
1311,534,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
1505,612,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",11.89
1571,637,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Sour ...",11.89
1590,644,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.89
1816,734,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.89
2401,953,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Guaca...",11.89
2439,969,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.89
2600,1032,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",9.39
2624,1042,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Sour Cream,...",9.39
2740,1088,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.89
2804,1114,1,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",11.89
2957,1176,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",11.89
3098,1235,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",9.39
3120,1244,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
3350,1343,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Cheese, Guacamole, Lettu...",11.89
3493,1403,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
4036,1615,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",9.39
4241,1693,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",9.39
4313,1720,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
4391,1752,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Pinto Beans...",9.39
4419,1762,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",9.39
4547,1807,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",9.39
4572,1818,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",9.39

### Step 6. Sort by the name of the item

In [37]:
chipo.sort_values(by='item_name', ascending=True)

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
3422,1373,1,6 Pack Soft Drink,[Coke],6.49
553,230,1,6 Pack Soft Drink,[Diet Coke],6.49
1916,774,1,6 Pack Soft Drink,[Diet Coke],6.49
1922,776,1,6 Pack Soft Drink,[Coke],6.49
1937,784,1,6 Pack Soft Drink,[Diet Coke],6.49
3836,1537,1,6 Pack Soft Drink,[Coke],6.49
298,129,1,6 Pack Soft Drink,[Sprite],6.49
1976,798,1,6 Pack Soft Drink,[Diet Coke],6.49
1167,481,1,6 Pack Soft Drink,[Coke],6.49
3875,1554,1,6 Pack Soft Drink,[Diet Coke],6.49
1124,465,1,6 Pack Soft Drink,[Coke],6.49
3886,1558,1,6 Pack Soft Drink,[Diet Coke],6.49
2108,849,1,6 Pack Soft Drink,[Coke],6.49
3010,1196,1,6 Pack Soft Drink,[Diet Coke],6.49
4535,1803,1,6 Pack Soft Drink,[Lemonade],6.49
4169,1664,1,6 Pack Soft Drink,[Diet Coke],6.49
4174,1666,1,6 Pack Soft Drink,[Coke],6.49
4527,1800,1,6 Pack Soft Drink,[Diet Coke],6.49
4522,1798,1,6 Pack Soft Drink,[Diet Coke],6.49
3806,1525,1,6 Pack Soft Drink,[Sprite],6.49
2389,949,1,6 Pack Soft Drink,[Coke],6.49
3132,1248,1,6 Pack Soft Drink,[Diet Coke],6.49
3141,1253,1,6 Pack Soft Drink,[Lemonade],6.49
639,264,1,6 Pack Soft Drink,[Diet Coke],6.49
1026,422,1,6 Pack Soft Drink,[Sprite],6.49
...,...,...,...,...,...
2996,1192,1,Veggie Salad,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
3163,1263,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
4084,1635,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
1694,686,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
2756,1094,1,Veggie Salad,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.49
4201,1677,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.25
1884,760,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
455,195,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
3223,1289,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
2223,896,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, Fajita Vegetables]",8.75
2269,913,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
4541,1805,1,Veggie Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",8.75
3293,1321,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
960,394,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
1316,536,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
2156,869,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
4261,1700,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
295,128,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",11.25
4573,1818,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75
2683,1066,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
496,207,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...",11.25
4109,1646,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [45]:
chipo.sort_values(by="item_price", ascending=False).head(1)

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

### Step 8. How many times were a Veggie Salad Bowl ordered?

In [50]:
chipo[chipo['item_name'] == 'Veggie Salad Bowl'].count()

order_id              18
quantity              18
item_name             18
choice_description    18
item_price            18
dtype: int64

### Step 9. How many times people orderd more than one Canned Soda?

In [64]:
len(chipo[(chipo['quantity']>1) & (chipo['item_name'] == 'Canned Soda')])

20